[build-system]
requires = [
    "setuptools",
    "setuptools-scm",
    "levenshtein==0.19.2",
    "unidecode==1.3.4",
    "mypy==0.961",
    ]
build-backend = "setuptools.build_meta"

[tool.black]
line_length=88

[tool.isort]
profile="black"

[tool.cibuildwheel]
skip="pp*"