steps:
- uses: actions/checkout@master
- uses: codecov/codecov-action@v2
  with:
    files: ./coverage1.xml,./coverage2.xml
    flags: unittests
    name: codecov-umbrella
    fail_ci_if_error: true
    verbose: true